#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 29 12:01:45 2019

@author: Home
"""

import random

number_of_players = 0
while number_of_players == 0:
    print('How many players? ')
    number_of_players = int(input())


game= GamePlay(number_of_players)
game.play()
game.start()

class Card(object):
    NUM = (2,3,4,5,6,7,8,9,10,11,12,13,14)

    SUIT = ('Clubs','Spades','Hearts','Diamonds')

    def __init__(self, rank, suit):
        self.rank = rank
        self.suit = suit

    def __face__(self):
        if self.rank == 14:
            rank = 'ACE'
        elif self.rank == 13:
            rank = 'King'
        elif self.rank == 12:
            rank = 'Queen'
        elif self.rank == 11:
            rank = 'Jack'
        else:
            rank = self.rank
        return str(rank) + " of " + self.suit
    
    def __eq__(self,other): # equal to
        return self.rank == other.rank
        
    def __lt__(self,other): # lesss than
        return self.rank < other.rank
        
    def __gt__(self,other): # greater than
        return self.rank > other.rank

class Deck(object):
    def __init__(self):
        self.deck = []
        for suit in Card.SUIT:
            for rank in Card.NUM:
                card = Card(rank,suit)
                self.deck.append(card)

    def shuffle(self):
        random.shuffle(self.deck)

    def __len__(self):
        return len(self.deck)

    def deal(self):
        if len(self) < 6:
            return None
        else:
            self.deck.pop(0)


class GamePlay(object):
    def __init__(self,number_of_players):
        self.deck = Deck()
        self.deck.shuffle()
        self.hands = []
        numCards_in_Hand = 0

        for i in range(number_of_players):
            hand = []
            for j in range(numCards_in_Hand):
                hand.append(self.deck.deal())
                self.hands.append(hand)
       
    def play(self):
        for i in range(len(self.hands)):
            sortedHand = sorted(self.hands[i], reverse = True)
            hand = 'idk'
            for card in sortedHand:
                hand = hand + str(card) + ' '
                print('Hand: ' + str(i + 1) + ': ' + hand)
    
    def highCard(self,hand):
        self.hand = hand
        
    
    def start(self):
        print('Welcome to Poker!')
        #number_of_players = eval(input('How many players? '))
        #while number_of_players == 0:
           # print('How many players? ')
            #number_of_players = int(input())
        game = GamePlay(number_of_players)
        game.play()  
        
        print('\n')
        for i in range(number_of_players):
            gameHand = game.hands[i]
            print("Hand " + str(i+1) + ": ", end='')
            GamePlay.highCard(gameHand)














